#footprint: [[0.25, 0.25], [0.25, -0.25], [-0.25, -0.25], [-0.25 0.25]]
robot_radius: 0.2
footprint_padding: 0.00
transform_tolerance: 0.2
map_type: costmap
always_send_full_costmap: true

obstacle_layer:
  enabled: true
  max_obstacle_height: 1.2
  min_obstacle_height: 0.0
  inflation_radius: 0.03
  obstacle_range: 2.0
  raytrace_range: 3.0
  combination_method: 1
  track_unknow_space: true
  observation_sources: scan
  scan: 
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    max_obstacle_height: 0.2
    min_obstacle_height: 0.0

inflation_layer: 
  enable: true
  cost_scaling_factor: 10
  inflation_radius: 0.05

static_layer:
  enabled: true
  map_topic: "/map"

